import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full bg-neutral-950 text-neutral-50`}
      >
        {/* Global background */}
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <div className="absolute inset-0 bg-neutral-950" />
          <div className="pointer-events-none absolute -top-40 -left-40 h-80 w-80 rounded-full bg-linear-to-br from-blue-500/30 via-purple-500/20 to-pink-500/10 blur-3xl" />
          <div className="pointer-events-none absolute bottom-[-120px] right-[-120px] h-96 w-96 rounded-full bg-linear-to-tr from-emerald-500/20 via-cyan-500/10 to-blue-500/0 blur-3xl" />
          <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(255,255,255,0.08)_0,_transparent_55%)]" />
        </div>

        {/* App content */}
        <div className="relative min-h-screen">
          <Toaster position="top-right" />
          {children}
        </div>
      </body>
    </html>
  );
}
